//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoNameGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoNameGame.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback.
        /// </summary>
        public static string About_FeedbackButton {
            get {
                return ResourceManager.GetString("About_FeedbackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string About_VersionTextBlock {
            get {
                return ResourceManager.GetString("About_VersionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string AboutPage_CreditsButton {
            get {
                return ResourceManager.GetString("AboutPage_CreditsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like us!.
        /// </summary>
        public static string AboutPage_LikeUsButton {
            get {
                return ResourceManager.GetString("AboutPage_LikeUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game feedback.
        /// </summary>
        public static string AboutPage_SendFeedback_EmailTitle {
            get {
                return ResourceManager.GetString("AboutPage_SendFeedback_EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out {0} for Windows Phone!.
        /// </summary>
        public static string AboutPage_ShareTaskTitle {
            get {
                return ResourceManager.GetString("AboutPage_ShareTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share:.
        /// </summary>
        public static string AboutPage_TextBlock_Share {
            get {
                return ResourceManager.GetString("AboutPage_TextBlock_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate:.
        /// </summary>
        public static string AboutPage_TextBlockRate {
            get {
                return ResourceManager.GetString("AboutPage_TextBlockRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete easy level group..
        /// </summary>
        public static string Achievement_EasyFinished {
            get {
                return ResourceManager.GetString("Achievement_EasyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journeyman.
        /// </summary>
        public static string Achievement_EasyFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_EasyFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Invert it! on facebook through &quot;about&quot; page..
        /// </summary>
        public static string Achievement_FacebookLike_Description {
            get {
                return ResourceManager.GetString("Achievement_FacebookLike_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporter.
        /// </summary>
        public static string Achievement_FacebookLike_Name {
            get {
                return ResourceManager.GetString("Achievement_FacebookLike_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete a level in less than 5 seconds on easy level group..
        /// </summary>
        public static string Achievement_GameTime1 {
            get {
                return ResourceManager.GetString("Achievement_GameTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete a level in less than 7 seconds on medium level group..
        /// </summary>
        public static string Achievement_GameTime2 {
            get {
                return ResourceManager.GetString("Achievement_GameTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightning fast.
        /// </summary>
        public static string Achievement_GameTime2_Name {
            get {
                return ResourceManager.GetString("Achievement_GameTime2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete a level in less than 10 seconds on hard level group..
        /// </summary>
        public static string Achievement_GameTime3 {
            get {
                return ResourceManager.GetString("Achievement_GameTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruler of the time.
        /// </summary>
        public static string Achievement_GameTime3_Name {
            get {
                return ResourceManager.GetString("Achievement_GameTime3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete hard level group..
        /// </summary>
        public static string Achievement_HardFinished {
            get {
                return ResourceManager.GetString("Achievement_HardFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Achievement_HardFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_HardFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete medium level group..
        /// </summary>
        public static string Achievement_MediumFinished {
            get {
                return ResourceManager.GetString("Achievement_MediumFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholar.
        /// </summary>
        public static string Achievement_MeiumFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_MeiumFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infallible.
        /// </summary>
        public static string Achievement_NoUndo_Name {
            get {
                return ResourceManager.GetString("Achievement_NoUndo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete 50 levels with perfect status..
        /// </summary>
        public static string Achievement_PerfectCount1 {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pioneer.
        /// </summary>
        public static string Achievement_PerfectCount1_Finished {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount1_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete 100 levels with perfect status..
        /// </summary>
        public static string Achievement_PerfectCount2 {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeker of the ideal.
        /// </summary>
        public static string Achievement_PerfectCount2_Finished {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount2_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete 150 levels with perfect status..
        /// </summary>
        public static string Achievement_PerfectCount3 {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfectionist.
        /// </summary>
        public static string Achievement_PerfectCount3_Finished {
            get {
                return ResourceManager.GetString("Achievement_PerfectCount3_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play for {0} days in a row. Receive {1} FREE hints!.
        /// </summary>
        public static string Achievement_PlayEveryDay_Description {
            get {
                return ResourceManager.GetString("Achievement_PlayEveryDay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addicted.
        /// </summary>
        public static string Achievement_PlayEveryDay_Name {
            get {
                return ResourceManager.GetString("Achievement_PlayEveryDay_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Invert it! through &quot;about&quot; page..
        /// </summary>
        public static string Achievement_RateApp_Description {
            get {
                return ResourceManager.GetString("Achievement_RateApp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string Achievement_RateApp_Name {
            get {
                return ResourceManager.GetString("Achievement_RateApp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete easy level group in Shapes pack..
        /// </summary>
        public static string Achievement_ShapesEasyFinished_Description {
            get {
                return ResourceManager.GetString("Achievement_ShapesEasyFinished_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight.
        /// </summary>
        public static string Achievement_ShapesEasyFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_ShapesEasyFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete hard level group in Shapes pack..
        /// </summary>
        public static string Achievement_ShapesHardFinished_Description {
            get {
                return ResourceManager.GetString("Achievement_ShapesHardFinished_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paladin.
        /// </summary>
        public static string Achievement_ShapesHardFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_ShapesHardFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete medium level group in Shapes pack..
        /// </summary>
        public static string Achievement_ShapesMediumFinished_Decription {
            get {
                return ResourceManager.GetString("Achievement_ShapesMediumFinished_Decription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cavalier.
        /// </summary>
        public static string Achievement_ShapesMediumFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_ShapesMediumFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play for 90 minutes total..
        /// </summary>
        public static string Achievement_TotalGameTime {
            get {
                return ResourceManager.GetString("Achievement_TotalGameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The longest journey.
        /// </summary>
        public static string Achievement_TotalGameTime_Name {
            get {
                return ResourceManager.GetString("Achievement_TotalGameTime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert 10000 dots..
        /// </summary>
        public static string Achievement_TotalInvertCount {
            get {
                return ResourceManager.GetString("Achievement_TotalInvertCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform 500 moves..
        /// </summary>
        public static string Achievement_TotalMoveCount {
            get {
                return ResourceManager.GetString("Achievement_TotalMoveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taps Emperor.
        /// </summary>
        public static string Achievement_TotalMoveCount_Name {
            get {
                return ResourceManager.GetString("Achievement_TotalMoveCount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete tutorial..
        /// </summary>
        public static string Achievement_TutorialFinished {
            get {
                return ResourceManager.GetString("Achievement_TutorialFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rookie.
        /// </summary>
        public static string Achievement_TutorialFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_TutorialFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish 9x9 ultra pack..
        /// </summary>
        public static string Achievement_Ultra9X9Finished_Description {
            get {
                return ResourceManager.GetString("Achievement_Ultra9X9Finished_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete warmup..
        /// </summary>
        public static string Achievement_WarmupFinished {
            get {
                return ResourceManager.GetString("Achievement_WarmupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprentice.
        /// </summary>
        public static string Achievement_WarmupFinished_Name {
            get {
                return ResourceManager.GetString("Achievement_WarmupFinished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a streak of 5, perfect wins on easy level group..
        /// </summary>
        public static string Achievement_WonStreak1 {
            get {
                return ResourceManager.GetString("Achievement_WonStreak1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steady.
        /// </summary>
        public static string Achievement_WonStreak1_Name {
            get {
                return ResourceManager.GetString("Achievement_WonStreak1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a streak of 5, perfect wins on medium level group..
        /// </summary>
        public static string Achievement_WonStreak2 {
            get {
                return ResourceManager.GetString("Achievement_WonStreak2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock solid.
        /// </summary>
        public static string Achievement_WonStreak2_Name {
            get {
                return ResourceManager.GetString("Achievement_WonStreak2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a streak of 5, perfect wins on hard level group..
        /// </summary>
        public static string Achievement_WonStreak3 {
            get {
                return ResourceManager.GetString("Achievement_WonStreak3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irresistible.
        /// </summary>
        public static string Achievement_WonStreak3_Name {
            get {
                return ResourceManager.GetString("Achievement_WonStreak3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        public static string AchievementsPage_Title {
            get {
                return ResourceManager.GetString("AchievementsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ingame periodical animation.
        /// </summary>
        public static string AnimationsPage_Description {
            get {
                return ResourceManager.GetString("AnimationsPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animations.
        /// </summary>
        public static string AnimationsPivotItem_Title {
            get {
                return ResourceManager.GetString("AnimationsPivotItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVERT IT!.
        /// </summary>
        public static string ApplicationTitle_CAPITAL {
            get {
                return ResourceManager.GetString("ApplicationTitle_CAPITAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invert it!.
        /// </summary>
        public static string ApplicationTitle_Normal {
            get {
                return ResourceManager.GetString("ApplicationTitle_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfectly finish a level in the ultra 9x9 hard group, not undoing any moves..
        /// </summary>
        public static string AppResources_Achievement_NoUndo {
            get {
                return ResourceManager.GetString("AppResources.Achievement_NoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almighty.
        /// </summary>
        public static string AppResources_Achievement_Ultra9X9Finished_Name {
            get {
                return ResourceManager.GetString("AppResources.Achievement_Ultra9X9Finished_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love You to rate our game 5 stars. Your feedback help us to continue work on the app, and make it better!.
        /// </summary>
        public static string AskForRating_Content {
            get {
                return ResourceManager.GetString("AskForRating_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RATE US!.
        /// </summary>
        public static string AskForRating_Title {
            get {
                return ResourceManager.GetString("AskForRating_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string CreditsPage_Title {
            get {
                return ResourceManager.GetString("CreditsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game progress:.
        /// </summary>
        public static string Dashboard_GameProgres_TextBlock {
            get {
                return ResourceManager.GetString("Dashboard_GameProgres_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new!.
        /// </summary>
        public static string Dashboard_IsNewTextBlock_Text {
            get {
                return ResourceManager.GetString("Dashboard_IsNewTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ready for a challange?.
        /// </summary>
        public static string DashBoardList_AchievementsDescription {
            get {
                return ResourceManager.GetString("DashBoardList_AchievementsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        public static string DashboardList_AchievementsTitle {
            get {
                return ResourceManager.GetString("DashboardList_AchievementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how to play.
        /// </summary>
        public static string DashboardList_Helpescription {
            get {
                return ResourceManager.GetString("DashboardList_Helpescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string DashboardList_HelpTitle {
            get {
                return ResourceManager.GetString("DashboardList_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customize application settings.
        /// </summary>
        public static string DashboardList_SettingsDescription {
            get {
                return ResourceManager.GetString("DashboardList_SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string DashboardList_SettingsTitle {
            get {
                return ResourceManager.GetString("DashboardList_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your favorite colors!.
        /// </summary>
        public static string DashboardList_ThemesDescription {
            get {
                return ResourceManager.GetString("DashboardList_ThemesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        public static string DashboardList_ThemesTitle {
            get {
                return ResourceManager.GetString("DashboardList_ThemesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.windowsphone.com/pl-pl/store/app/.
        /// </summary>
        public static string GameMarketPlaceUrl {
            get {
                return ResourceManager.GetString("GameMarketPlaceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase hints.
        /// </summary>
        public static string GamePage_AppBar_PurchaseHints {
            get {
                return ResourceManager.GetString("GamePage_AppBar_PurchaseHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redo.
        /// </summary>
        public static string GamePage_AppBar_Redo {
            get {
                return ResourceManager.GetString("GamePage_AppBar_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        public static string GamePage_AppBar_Undo {
            get {
                return ResourceManager.GetString("GamePage_AppBar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next level.
        /// </summary>
        public static string GamePage_ApplicaitonBar_Next_level {
            get {
                return ResourceManager.GetString("GamePage_ApplicaitonBar_Next_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to achievements.
        /// </summary>
        public static string GamePage_ApplicationBar_Achievements {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redo.
        /// </summary>
        public static string GamePage_ApplicationBar_Redo {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        public static string GamePage_ApplicationBar_Restart {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string GamePage_ApplicationBar_Settings {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        public static string GamePage_ApplicationBar_Themes {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo.
        /// </summary>
        public static string GamePage_ApplicationBar_Undo {
            get {
                return ResourceManager.GetString("GamePage_ApplicationBar_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL .
        /// </summary>
        public static string GamePage_LevelTextBlock {
            get {
                return ResourceManager.GetString("GamePage_LevelTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves: .
        /// </summary>
        public static string GamePage_MovesTextBlock {
            get {
                return ResourceManager.GetString("GamePage_MovesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfect: .
        /// </summary>
        public static string GamePage_PerfectTextBlock {
            get {
                return ResourceManager.GetString("GamePage_PerfectTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hints.
        /// </summary>
        public static string GamePage_RefreshHintsCountButton_CurrentHints {
            get {
                return ResourceManager.GetString("GamePage_RefreshHintsCountButton_CurrentHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more hints.
        /// </summary>
        public static string GamePage_RefreshHintsCountButton_MoreHints {
            get {
                return ResourceManager.GetString("GamePage_RefreshHintsCountButton_MoreHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart.
        /// </summary>
        public static string GamePage_ResetMenuItem_Text {
            get {
                return ResourceManager.GetString("GamePage_ResetMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string GamePaused_Button_Levels {
            get {
                return ResourceManager.GetString("GamePaused_Button_Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string GamePaused_ResumeButton_Content {
            get {
                return ResourceManager.GetString("GamePaused_ResumeButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME PAUSED.
        /// </summary>
        public static string GamePaused_Title {
            get {
                return ResourceManager.GetString("GamePaused_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO PLAY.
        /// </summary>
        public static string GameTutorial_Header {
            get {
                return ResourceManager.GetString("GameTutorial_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level is.
        /// </summary>
        public static string GameTutorial_Step2_TextBlock1 {
            get {
                return ResourceManager.GetString("GameTutorial_Step2_TextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  completed.
        /// </summary>
        public static string GameTutorial_Step2_TextBlock2 {
            get {
                return ResourceManager.GetString("GameTutorial_Step2_TextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  when You change all dots to the one.
        /// </summary>
        public static string GameTutorial_Step2_TextBlock3 {
            get {
                return ResourceManager.GetString("GameTutorial_Step2_TextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  color..
        /// </summary>
        public static string GameTutorial_Step2_TextBlock4 {
            get {
                return ResourceManager.GetString("GameTutorial_Step2_TextBlock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The less moves.
        /// </summary>
        public static string GameTutorial_Step3_TextBLock1 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBLock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You make to finish a level....
        /// </summary>
        public static string GameTutorial_Step3_TextBLock2 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBLock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...the more stars.
        /// </summary>
        public static string GameTutorial_Step3_TextBLock3 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBLock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You get!.
        /// </summary>
        public static string GameTutorial_Step3_TextBLock4 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBLock4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use stars.
        /// </summary>
        public static string GameTutorial_Step3_TextBLock5 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBLock5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to unlock.
        /// </summary>
        public static string GameTutorial_Step3_TextBlock6 {
            get {
                return ResourceManager.GetString("GameTutorial_Step3_TextBlock6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to many colorful.
        /// </summary>
        public static string GameTutorialControl_Step3_TextBlock7 {
            get {
                return ResourceManager.GetString("GameTutorialControl_Step3_TextBlock7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        public static string GameTutorialControl_Step3_TextBlock8 {
            get {
                return ResourceManager.GetString("GameTutorialControl_Step3_TextBlock8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.
        /// </summary>
        public static string GameTutorialControl_Step3_TextBlock9 {
            get {
                return ResourceManager.GetString("GameTutorialControl_Step3_TextBlock9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , specific.
        /// </summary>
        public static string GameTutorialStep2_GoalTextBlock {
            get {
                return ResourceManager.GetString("GameTutorialStep2_GoalTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blocks do nothing when tapped and cannot be inverted..
        /// </summary>
        public static string GameTutorialStep3_Text2_Disabled {
            get {
                return ResourceManager.GetString("GameTutorialStep3_Text2_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled .
        /// </summary>
        public static string GameTutorialStep3_Text2_Disabled_Prefix {
            get {
                return ResourceManager.GetString("GameTutorialStep3_Text2_Disabled_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  disabled .
        /// </summary>
        public static string GameTutorialStep4_Text1_Disabled {
            get {
                return ResourceManager.GetString("GameTutorialStep4_Text1_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block is introduced:.
        /// </summary>
        public static string GameTutorialStep4_Text1_Postfix {
            get {
                return ResourceManager.GetString("GameTutorialStep4_Text1_Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this level pack, a new.
        /// </summary>
        public static string GameTutorialStep4_Text1_Prefix {
            get {
                return ResourceManager.GetString("GameTutorialStep4_Text1_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string GameWon_LevelsButton_Content {
            get {
                return ResourceManager.GetString("GameWon_LevelsButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves.
        /// </summary>
        public static string GameWonControl_MovesCaptionMany {
            get {
                return ResourceManager.GetString("GameWonControl_MovesCaptionMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You completed the level in.
        /// </summary>
        public static string GameWonControl_MovesDescriptionTextBlock {
            get {
                return ResourceManager.GetString("GameWonControl_MovesDescriptionTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move.
        /// </summary>
        public static string GameWonControlModel_MovesCountCaption_Single {
            get {
                return ResourceManager.GetString("GameWonControlModel_MovesCountCaption_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New theme unlocked!.
        /// </summary>
        public static string GameWonPopup_NewItemUnlocked {
            get {
                return ResourceManager.GetString("GameWonPopup_NewItemUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next level.
        /// </summary>
        public static string GameWonPopup_NextLevelButton {
            get {
                return ResourceManager.GetString("GameWonPopup_NextLevelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart level.
        /// </summary>
        public static string GameWonPopup_RestartLevelButton {
            get {
                return ResourceManager.GetString("GameWonPopup_RestartLevelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string HelpPage_Goal_Title {
            get {
                return ResourceManager.GetString("HelpPage_Goal_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete each level you must change all dots to the one, &quot;goal&quot; color. It is visible all the time during the game..
        /// </summary>
        public static string HelpPage_GoalTextBlock {
            get {
                return ResourceManager.GetString("HelpPage_GoalTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board consists of dots of two colors. When a dot is tapped all neighbouring dots get inverted, changing color..
        /// </summary>
        public static string HelpPage_Rules_TextBox {
            get {
                return ResourceManager.GetString("HelpPage_Rules_TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string HelpPage_RulesTitle {
            get {
                return ResourceManager.GetString("HelpPage_RulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each level can be completed with a number of moves (taps). The less moves are made the more stars will be awarded for completing it..
        /// </summary>
        public static string HelpPage_Stars_TextBlock1 {
            get {
                return ResourceManager.GetString("HelpPage_Stars_TextBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars can be used to unlock colorful themes..
        /// </summary>
        public static string HelpPage_Stars_TextBlock2 {
            get {
                return ResourceManager.GetString("HelpPage_Stars_TextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can You unlock them all?.
        /// </summary>
        public static string HelpPage_Stars_TextBlock3 {
            get {
                return ResourceManager.GetString("HelpPage_Stars_TextBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string HelpPage_Stars_Title {
            get {
                return ResourceManager.GetString("HelpPage_Stars_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpPage_Title {
            get {
                return ResourceManager.GetString("HelpPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MainPage_About_Title {
            get {
                return ResourceManager.GetString("MainPage_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dashboard.
        /// </summary>
        public static string MainPage_Dashboard_Title {
            get {
                return ResourceManager.GetString("MainPage_Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to goal:.
        /// </summary>
        public static string MainPage_GoaltextBlock {
            get {
                return ResourceManager.GetString("MainPage_GoaltextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More levels coming soon!.
        /// </summary>
        public static string MainPage_MoreLevelsBaner {
            get {
                return ResourceManager.GetString("MainPage_MoreLevelsBaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new game.
        /// </summary>
        public static string MainPage_NewGame_Title {
            get {
                return ResourceManager.GetString("MainPage_NewGame_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play without ads! Help authors!.
        /// </summary>
        public static string MainPage_RemoveAdsButtonDescription {
            get {
                return ResourceManager.GetString("MainPage_RemoveAdsButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ads.
        /// </summary>
        public static string MainPage_RemoveAdsButtonText {
            get {
                return ResourceManager.GetString("MainPage_RemoveAdsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OnOffConverter_Convert_Off {
            get {
                return ResourceManager.GetString("OnOffConverter_Convert_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnOffConverter_Convert_On {
            get {
                return ResourceManager.GetString("OnOffConverter_Convert_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEARED!.
        /// </summary>
        public static string PointsToHeaderConverter_Convert_Good {
            get {
                return ResourceManager.GetString("PointsToHeaderConverter_Convert_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERFECT!.
        /// </summary>
        public static string PointsToHeaderConverter_Convert_Perfect {
            get {
                return ResourceManager.GetString("PointsToHeaderConverter_Convert_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have .
        /// </summary>
        public static string PuchaseHints_HintsCount_Description1 {
            get {
                return ResourceManager.GetString("PuchaseHints_HintsCount_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  hints.
        /// </summary>
        public static string PuchaseHints_HintsCount_Description2 {
            get {
                return ResourceManager.GetString("PuchaseHints_HintsCount_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase any pack to remove ads!.
        /// </summary>
        public static string PurchaseHintsPage_AdsHint {
            get {
                return ResourceManager.GetString("PurchaseHintsPage_AdsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase hints.
        /// </summary>
        public static string PurchaseHintsPage_Title {
            get {
                return ResourceManager.GetString("PurchaseHintsPage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement unlocked!.
        /// </summary>
        public static string SendToastHandler_Title {
            get {
                return ResourceManager.GetString("SendToastHandler_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string SettingPage_SoundSwitch_Header {
            get {
                return ResourceManager.GetString("SettingPage_SoundSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string SettingsControl_ResetProgressMessageBox_ButtonNo {
            get {
                return ResourceManager.GetString("SettingsControl_ResetProgressMessageBox_ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string SettingsControl_ResetProgressMessageBox_ButtonYes {
            get {
                return ResourceManager.GetString("SettingsControl_ResetProgressMessageBox_ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset progress.
        /// </summary>
        public static string SettingsControl_ResetProgressMessageBox_Caption {
            get {
                return ResourceManager.GetString("SettingsControl_ResetProgressMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all the progress? This include levels and unlocked content..
        /// </summary>
        public static string SettingsControl_ResetProgressMessageBox_Mesage {
            get {
                return ResourceManager.GetString("SettingsControl_ResetProgressMessageBox_Mesage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu music.
        /// </summary>
        public static string SettingsPage_MusicSwitch_Header {
            get {
                return ResourceManager.GetString("SettingsPage_MusicSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset progress.
        /// </summary>
        public static string SettingsPage_ResetProgressButton_Content {
            get {
                return ResourceManager.GetString("SettingsPage_ResetProgressButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master volume.
        /// </summary>
        public static string SettingsPage_SoundVolumeTextBlock {
            get {
                return ResourceManager.GetString("SettingsPage_SoundVolumeTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string SettingsPage_VibrationSwitch_Header {
            get {
                return ResourceManager.GetString("SettingsPage_VibrationSwitch_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        public static string SingleAchievemenControl_TextBlock_Incomplete {
            get {
                return ResourceManager.GetString("SingleAchievemenControl_TextBlock_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET ADDICTED!.
        /// </summary>
        public static string StartAppEveryDayMessageDisplayer_Caption {
            get {
                return ResourceManager.GetString("StartAppEveryDayMessageDisplayer_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Invert it! for {0} days in a row to unlock &quot;Addicted&quot; achievement and get {1} FREE hints!.
        /// </summary>
        public static string StartAppEveryDayMessageDisplayer_Message {
            get {
                return ResourceManager.GetString("StartAppEveryDayMessageDisplayer_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem solving this level?.
        /// </summary>
        public static string SuggestWithMessageBox_Caption {
            get {
                return ResourceManager.GetString("SuggestWithMessageBox_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You want to get some hints?.
        /// </summary>
        public static string SuggestWithMessageBox_Text {
            get {
                return ResourceManager.GetString("SuggestWithMessageBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose your favorite colors!.
        /// </summary>
        public static string ThemesPage_Description {
            get {
                return ResourceManager.GetString("ThemesPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        public static string ThemesPage_PlayerStars_Text {
            get {
                return ResourceManager.GetString("ThemesPage_PlayerStars_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        public static string ThemesPage_Title {
            get {
                return ResourceManager.GetString("ThemesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to themes.
        /// </summary>
        public static string ThemesPivotItem_Title {
            get {
                return ResourceManager.GetString("ThemesPivotItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string Tutorial_Page1_Text1 {
            get {
                return ResourceManager.GetString("Tutorial_Page1_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the dot to invert its neighbours..
        /// </summary>
        public static string Tutorial_Page1_Text2 {
            get {
                return ResourceManager.GetString("Tutorial_Page1_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNLOCKS.
        /// </summary>
        public static string UnlocksPage_Title {
            get {
                return ResourceManager.GetString("UnlocksPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you played today?.
        /// </summary>
        public static string UpdateLiveTileGameWonAction_BackContent_Temp {
            get {
                return ResourceManager.GetString("UpdateLiveTileGameWonAction_BackContent_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game progress.
        /// </summary>
        public static string UpdateLiveTileGameWonAction_BackTitle {
            get {
                return ResourceManager.GetString("UpdateLiveTileGameWonAction_BackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You earned {0} stars in last game..
        /// </summary>
        public static string UpdateLiveTileGameWonAction_BackTitle_Temp {
            get {
                return ResourceManager.GetString("UpdateLiveTileGameWonAction_BackTitle_Temp", resourceCulture);
            }
        }
    }
}
